namespace FirebirdTraceAnalyzer.Models.Reports;

/// <summary>
/// Report footer.
/// </summary>
public sealed class ReportFooter
{
    /// <summary>Whether to show the footer.</summary>
    public bool Show { get; init; } = true;

    /// <summary>Footer text.</summary>
    public string Text { get; init; } = "Generated by Firebird Trace Analyzer";

    /// <summary>Whether to show page numbers.</summary>
    public bool ShowPageNumbers { get; init; } = true;

    /// <summary>Page-number format string.</summary>
    public string PageNumberFormat { get; init; } = "Page {0} of {1}";
}